### PR TITLE
Explicitly set texturepath in config file

### LINKED ISSUE #29: Overviewer not finding textures with 1.13.2.jar ?
The 1.13.2.jar downloads but then overviewer doesn't find it

```
$ docker run   --rm   -e MINECRAFT_VERSION="1.13.2"   -v /Users/[me]/Desktop/[minecraft_server]:/home/minecraft/server/:ro   -v /Users/[me]/Desktop/[minecraft_server_map]:/home/minecraft/render/:rw   mide/minecraft-overviewer:latest
Using Client URL https://launcher.mojang.com/v1/objects/30bfe37a8db404db11c7edf02cb5165817afb4d9/client.jar.
WARNING: timestamping does nothing in combination with -O. See the manual
for details.

--2019-02-28 01:28:01--  https://launcher.mojang.com/v1/objects/30bfe37a8db404db11c7edf02cb5165817afb4d9/client.jar
Resolving launcher.mojang.com (launcher.mojang.com)... 54.192.147.10
Connecting to launcher.mojang.com (launcher.mojang.com)|54.192.147.10|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 16089640 (15M) [application/java-archive]
Saving to: '1.13.2.jar'

     0K .......... .......... .......... .......... ..........  0% 2.79M 5s
[spliced]
 15700K .......... ..                                         100% 8.04M=4.6s

2019-02-28 01:28:05 (3.31 MB/s) - '1.13.2.jar' saved [16089640/16089640]

2019-02-28 01:28:06  Welcome to Minecraft Overviewer!
2019-02-28 01:28:15  Generating textures...
*******************************************************************************
2019-02-28 01:28:15 E Could not find the textures while searching for 'assets/minecraft/textures/block/grass_block_top.png'. Try specifying the 'texturepath' option in your config file.
Set it to the path to a Minecraft Resource pack.
Alternately, install the Minecraft client (which includes textures)
Also see <http://docs.overviewer.org/en/latest/running/#installing-the-textures>
(Remember, this version of Overviewer requires a 1.13-compatible resource pack)
(Also note that I won't automatically use snapshots; you'll have to use the texturepath option to use a snapshot jar)
```

### PR DESCRIPTION
**Pull request by patricklucas**
Closes #29

### CODE REVIEW

**Comment by CNorris724** [comment]
I've tested this and it works.  Thank you!

**Comment by m0rff** [comment]
@patricklucas I noticed this pull request does not reflect all the commits you made on your fork. The texturepath option is not added to config.py. Only entrypoint.sh is changed

**Comment by mide** [comment]
Thanks for opening up the PR - I've been very busy but hope to have time to look through this soon.

**Comment by mide** [comment]
Good news, I am able to reproduce.

```
2019-04-27 14:31:42  Welcome to Minecraft Overviewer!
2019-04-27 14:31:42  Generating textures...
*******************************************************************************
2019-04-27 14:31:42 E Could not find the textures while searching for 'assets/minecraft/textures/block/grass_block_top.png'. Try specifying the 'texturepath' option in your config file.
Set it to the path to a Minecraft Resource pack.
Alternately, install the Minecraft client (which includes textures)
Also see <http://docs.overviewer.org/en/latest/running/#installing-the-textures>
(Remember, this version of Overviewer requires a 1.14-compatible resource pack)
(Also note that I won't automatically use snapshots; you'll have to use the texturepath option to use a snapshot jar)
```

**Comment by patricklucas** [comment]
> 
> 
> @patricklucas I noticed this pull request does not reflect all the commits you made on your fork. The texturepath option is not added to config.py. Only entrypoint.sh is changed

Hmm, no I think the HEAD commit of my fork is 650e0b9, the same as the commit in this PR. The `texturepath` line is added in the `entrypoint.sh` script, line 16 in the version in this PR. I didn't add it directly to `config.py` because its value depends on the `MINECRAFT_VERSION` environment variable---though another option would be to also read that env var from within the python script.

**Comment by mide** [comment]
@patricklucas I have actually just finished implementing your other suggestion (in your most recent comment) - What do you think? https://github.com/mide/minecraft-overviewer/pull/31

**Comment by mide** [comment]
Solved by #31.

**Pull request closed without merging**
