### PR TITLE
Allow render to run in a crontab

### PR DESCRIPTION
**Pull request by Ovski4**
Hi,

First thank you a lot for this docker image. It is really useful.

I would like to render the map periodically. I forked your repo to allow the render to be schedule in a crontab. If you think it can be useful, here are my changes.

Cheers

### CODE REVIEW

**Comment by mide** [comment]
Thanks for the contribution - I really appreciate it! 

Question about how you're trying to approach this: Could you have the `docker run` command run via a cron job on the host instead? If you're using Kubernetes, can you use [CronJobs](https://kubernetes.io/docs/tasks/job/automated-tasks-with-cron-jobs/)? Or if you're using AWS ECS, could you use [scheduled tasks](https://docs.aws.amazon.com/en_pv/AmazonECS/latest/developerguide/scheduling_tasks.html)?

I try to shy away from running `cron` inside a container [(writeup on this)](https://nickjanetakis.com/blog/docker-tip-40-running-cron-jobs-on-the-host-vs-in-a-container), so I'm curious if there is another way we could approach this problem.

**Comment by Ovski4** [comment]
This is interesting. I'm running containers in a small docker swarm. I don't think docker swarm provides an "official way" to deal with scheduled tasks.

My minecraft related containers are configured within a single stack. I like to have everything running from stacks. This way I just have to remove the stack without having to think about other configurations / dependencies such as a crontab.

But I can see there is a consensus to avoid running cron within a container, and I understand why.

**Comment by mide** [comment]
I can certainly understand running everything in a single stack. Could you perhaps expose a privileged container (one that can access the Docker swarm) and have it run the `cron `process? Or could you define the task to keep running, that way when it exits it will automatically restart?

**Comment by Ovski4** [comment]
Sounds good, I'll see what I can do!

**Pull request closed without merging**
